#define MAX_IDENT_LEN 11

typedef enum {//Các lo?i Token du?c s? d?ng trong PL/0
	NONE=0, IDENT, NUMBER,
	BEGIN, CALL, CONST, DO,  ELSE, END, FOR, IF, ODD,
	PROCEDURE, PROGRAM, THEN, TO, VAR, WHILE,WRITE,WRITELN,READ,READLN,
	PLUS, MINUS, TIMES, SLASH, EQU, NEQ, LSS, LEQ, GTR, GEQ, LPARENT, RPARENT, LBRACK, RBRACK, PERIOD, COMMA, SEMICOLON,  ASSIGN, PERCENT, NUMBERERROR, ENDOF,ARRAY, NOTDECLARE, SUCCESS,DECLARED
} TokenType;
char TokenTab[][15]={//Các lo?i Token du?c s? d?ng trong PL/0
	"NONE", "IDENT", "NUMBER",
	"BEGIN", "CALL", "CONST", "DO",  "ELSE", "END", "FOR", "IF", "ODD",
	"PROCEDURE", "PROGRAM", "THEN", "TO", "VAR","WHILE","WRITE","WRITELN", "READ", "READLN",
	"PLUS","MINUS","TIMES", "SLASH", "EQU", "NEQ", "LSS", "LEQ", "GTR", "GEQ", "LPARENT", "RPARENT", "LBRACK", "RBRACK", "PERIOD", "COMMA", "SEMICOLON",  "ASSIGN", "PERCENT", "NUMBERERROR"
} ;


